### ISSUE TITLE
Regex Extension

### ISSUE THREAD

**Issue by helo86** [JusticeRage/freedomfighting#5]
Hey,

awesome tools :)

I think in the nojail.py is the regex incomplete, e.g. /var/log/auth will not be cleaned while testing. 
Line: 340  "-regex", ".*\.log(\.[0-9]+)(\.gz)?$"],

I changed it to: "-regex", ".*\.log|.*\.log(\.[0-9]+)(\.gz)?$"],
[*] 32 lines removed from /var/log/auth.log!

**Comment by helo86** [comment]
Sorry copy paste error:
I changed it to: "-regex", ".*\.log|.*\.log(\.[0-9]+)(\.gz)?$"],

**Comment by helo86** [comment]
`"-regex", ".*\.log|.*\.log(\.[0-9]+)(\.gz)?$"],`

**Comment by JusticeRage** [comment]
Hey! Thanks for your feedback. I've updated the regexp in a slightly different way, can you confirm that it works as expected?

**Comment by helo86** [comment]
perfect. works like a charm.
