### ISSUE TITLE
First ssh connection not recognized

### ISSUE THREAD

**Issue by helo86** [JusticeRage/freedomfighting#6]
Hi,

I could not figur out why but the first ssh connection to the host is not recognized by the script.
Perhaps you have an idea.

Kind regards,
helo

**Comment by JusticeRage** [comment]
Hi! Could you provide more details? At the moment, I'm not sure what is going on.

- What script are you referring to?
- What is the expected behavior? What is happening?
- Are there steps to reproduce the issue?

Thanks!

**Comment by helo86** [comment]
Hi. Of course, sorry I was so into the script that I thought it must be obvious what I was talking about...

So I started your autojack.py and the first connection made to that host is not recognized but as soon as I start a second connection over ssh it works from this point on and everything is logged. I tested it twice with the same result but with the same VM setup.
So the script does not recognice the first ssh connection to the host but after that everything works fine.

Hope this helps to understand it a bit better.

**Comment by JusticeRage** [comment]
Weird, it works fine for me. What distribution are you using? And with which user account are you testing (is it root?)?
Also, do you mean that the logging doesn't start for the current SSH session, i.e. the one which started autojack.py? Because this is expected behavior.

**Comment by helo86** [comment]
Hey,
sorry for my late response. In my second test the first conenction gets recognized and it works fine.
Thanks
